### ISSUE TITLE
Wrong spelling of the word 'usable' in the GitHub description.

### ISSUE THREAD

**Issue by EdwardBetts** [cbrueffer/tophat-recondition#4]
The word _usable_ is spelt incorrectly in the GitHub description.

**Comment by cbrueffer** [comment]
Thanks; I've changed it since `usable` appears to be the more common form. Please note that `useable` is perfectly fine though, see https://english.stackexchange.com/questions/69709/is-useable-preferred-in-certain-regions-or-just-an-alternate-spelling-of-usa and several of the online dictionaries (Collins, Merriam-Webster, etc).
